### ISSUE TITLE
Potential issue with running the library in Quasar under SSR mode

### ISSUE THREAD

**Issue by megasanjay** [megasanjay/vue3-marquee#181]
Posted on behalf of another user. Putting it in here for tracking purposes
```
[Vue Router warn]: uncaught error during route navigation:
Error [ERR_REQUIRE_ESM]: require() of ES Module /<PATH_TO_PROJECT>/node_modules/vue3-marquee/dist/vue3-marquee.cjs.js from /<PATH_TO_PROJECT> not supported.
vue3-marquee.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename vue3-marquee.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /<PATH_TO_PROJECT>/node_modules/vue3-marquee/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at _require (/<PATH_TO_PROJECT>[/node_modules/@quasar/ssr-helpers/lib/create-bundle.js:56:9](mailto:/node_modules/@quasar/ssr-helpers/lib/create-bundle.js:56:9))
    at vue3-marquee (render-app.js:578:18)
    at __webpack_require__ (render-app.js:602:41)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-1.use[0][!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/components/InDemandPackComponent.vue?vue&type=script&setup=true&lang=js](mailto:!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet%5b0%5d.use%5b0%5d!./node_modules/vue-loader/dist/index.js??ruleSet%5b0%5d.use%5b1%5d!./src/components/InDemandPackComponent.vue?vue&type=script&setup=true&lang=js) (chunk-src_pages_CompletePage_vue.js:176:70)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/components/InDemandPackComponent.vue?vue&type=script&setup=true&lang=js (chunk-src_pages_CompletePage_vue.js:671:327)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/components/InDemandPackComponent.vue (chunk-src_pages_CompletePage_vue.js:46:119)
    at __webpack_require__ (render-app.js:602:41)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-1.use[0][!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/pages/CompletePage.vue?vue&type=script&setup=true&lang=js](mailto:!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet%5b0%5d.use%5b0%5d!./node_modules/vue-loader/dist/index.js??ruleSet%5b0%5d.use%5b1%5d!./src/pages/CompletePage.vue?vue&type=script&setup=true&lang=js) (chunk-src_pages_CompletePage_vue.js:296:98)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/pages/CompletePage.vue?vue&type=script&setup=true&lang=js (chunk-src_pages_CompletePage_vue.js:701:318)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/pages/CompletePage.vue (chunk-src_pages_CompletePage_vue.js:104:110)
    at Function.__webpack_require__ (render-app.js:602:41) {
  code: 'ERR_REQUIRE_ESM'
}

[Quasar Dev Webserver] / -> error during render
Error [ERR_REQUIRE_ESM]: require() of ES Module /<PATH_TO_PROJECT>/node_modules/vue3-marquee/dist/vue3-marquee.cjs.js from /<PATH_TO_PROJECT> not supported.
vue3-marquee.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename vue3-marquee.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /<PATH_TO_PROJECT>/node_modules/vue3-marquee/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at _require (/<PATH_TO_PROJECT>[/node_modules/@quasar/ssr-helpers/lib/create-bundle.js:56:9](mailto:/node_modules/@quasar/ssr-helpers/lib/create-bundle.js:56:9))
    at vue3-marquee (render-app.js:578:18)
    at __webpack_require__ (render-app.js:602:41)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-1.use[0][!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/components/InDemandPackComponent.vue?vue&type=script&setup=true&lang=js](mailto:!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet%5b0%5d.use%5b0%5d!./node_modules/vue-loader/dist/index.js??ruleSet%5b0%5d.use%5b1%5d!./src/components/InDemandPackComponent.vue?vue&type=script&setup=true&lang=js) (chunk-src_pages_CompletePage_vue.js:176:70)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/components/InDemandPackComponent.vue?vue&type=script&setup=true&lang=js (chunk-src_pages_CompletePage_vue.js:671:327)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/components/InDemandPackComponent.vue (chunk-src_pages_CompletePage_vue.js:46:119)
    at __webpack_require__ (render-app.js:602:41)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-1.use[0][!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/pages/CompletePage.vue?vue&type=script&setup=true&lang=js](mailto:!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet%5b0%5d.use%5b0%5d!./node_modules/vue-loader/dist/index.js??ruleSet%5b0%5d.use%5b1%5d!./src/pages/CompletePage.vue?vue&type=script&setup=true&lang=js) (chunk-src_pages_CompletePage_vue.js:296:98)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/pages/CompletePage.vue?vue&type=script&setup=true&lang=js (chunk-src_pages_CompletePage_vue.js:701:318)
    at __webpack_require__ (render-app.js:602:41)
    at ./src/pages/CompletePage.vue (chunk-src_pages_CompletePage_vue.js:104:110)
    at Function.__webpack_require__ (render-app.js:602:41)
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at join (node:path:1175:7)
    at getFilename ([file:///<PATH_TO_PROJECT>/node_modules/@quasar/render-ssr-error/src/stack.js:12:26](file:///%3cPATH_TO_PROJECT%3e/node_modules/@quasar/render-ssr-error/src/stack.js:12:26))
    at getSource ([file:///<PATH_TO_PROJECT>/node_modules/@quasar/render-ssr-error/src/stack.js:21:20](file:///%3cPATH_TO_PROJECT%3e/node_modules/@quasar/render-ssr-error/src/stack.js:21:20))
    at [file:///<PATH_TO_PROJECT>/node_modules/@quasar/render-ssr-error/src/stack.js:63:38](file:///%3cPATH_TO_PROJECT%3e/node_modules/@quasar/render-ssr-error/src/stack.js:63:38)
    at Array.map (<anonymous>)
    at getStack ([file:///<PATH_TO_PROJECT>/node_modules/@quasar/render-ssr-error/src/stack.js:62:16](file:///%3cPATH_TO_PROJECT%3e/node_modules/@quasar/render-ssr-error/src/stack.js:62:16))
    at renderSSRError ([file:///<PATH_TO_PROJECT>/node_modules/@quasar/render-ssr-error/src/index.js:21:12](file:///%3cPATH_TO_PROJECT%3e/node_modules/@quasar/render-ssr-error/src/index.js:21:12))
    at Object.renderError [as error] (/<PATH_TO_PROJECT>[/node_modules/@quasar/app-webpack/lib/dev-server-ssr.js:28:3](mailto:/node_modules/@quasar/app-webpack/lib/dev-server-ssr.js:28:3))
    at eval (webpack://<PATH_TO_PROJECT>/./src-ssr/middlewares/render.js?:46:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.3.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by megasanjay** [comment]
I was able to resolve the issue by renaming the file extension from dist/vue3-marquee.cjs.js to dist/vue3-marquee.cjs and updating the same in your package.json file.
